#!/bin/sh
fpc analyzephpserializeddata.pas
fpc asn1util.pas
fpc cgi_get.pas
fpc ftpsend_jegas.pas
fpc ftptsend_jegas.pas
fpc httpsend.pas
fpc ipcclient.pas
fpc ipcserver.pas
fpc jas.pas
fpc jbu.pas
fpc jegasbackup.pas
fpc jegas_cgi_thin_client.pas
fpc jegasftp.pas
fpc jegas_http_requester.pas
fpc jegasrc.pas
fpc jrc.pas
fpc junzip.pas
fpc jzip-old.pas
fpc jzip.pas
fpc ldapsend.pas
fpc macfixpic.pas
fpc makedbcfile.pas
fpc numbers.pas
fpc readline.pas
fpc recursecmd.pas
fpc setup.pas
fpc slogsend.pas
fpc smtpsend_jas.pas
fpc sqlitetest.pas
fpc ssfpc.pas
fpc test_data_types.pas
fpc testdate.pas
fpc test_defaultformat_settings.pas
fpc testdns.pas
fpc test_filemodes.pas
fpc test_filename_parse.pas
fpc testformats.pas
fpc testhttp.pas
fpc test_jdate.pas
fpc test.pas
fpc teststdinout.pas
fpc testtprocess.pas
fpc test_uc_animate.pas
fpc test_uc_console.pas
fpc test_uc_sageui.pas
fpc test_ug_cgiout_ipc.pas
fpc test_ug_cgi.pas
fpc test_ug_common.pas
fpc test_ug_fileshare.pas
fpc test_ug_ipc_xxxx_file.pas
fpc test_ug_jado02.pas
fpc test_ug_jado.pas
fpc test_ug_jcrypt.pas
fpc test_ug_jegas.pas
fpc test_ug_jegas_revisions.pas
fpc test_ug_jfc_buffer.pas
fpc test_ug_jfc_dir.pas
fpc test_ug_jfc_dl.pas
fpc test_ug_jfc_fifo.pas
fpc test_ug_jfc_ini.pas
fpc test_ug_jfc_matrix.pas
fpc test_ug_jfc_tokenizer.pas
fpc test_ug_jfc_xdl.pas
fpc test_ug_jfc_xml2.pas
fpc test_ug_jfc_xml.pas
fpc test_ug_jfilesys_01.pas
fpc test_ug_jfilesys_02.pas
fpc test_ug_jfilesys_03.pas
fpc test_ug_mysql3.pas
fpc test_ug_mysql4.pas
fpc test_ug_pixelgrid.pas
fpc test_ug_rgba.pas
fpc test_ug_threadmgr01.pas
fpc test_ug_threadmgr02.pas
fpc test_ug_threadmgr.pas
fpc test_ug_usgs.pas
fpc test_ug_xyz.pas
fpc test_ug_zebra.pas
fpc testwave.pas
fpc TFTPDaemonThread.pas
fpc tlntsend.pas
fpc toke.pas
fpc tp.pas
fpc tui.pas
fpc ug_jfc_dir.pas
fpc wpt2txt.pas
