#!/bin/sh
fpc cgi_get                           
fpc ipcclient                         
fpc ipcserver                         
fpc jegas_http_requester              
fpc numbers                           
fpc readline                          
fpc smtpsend_jas                      
fpc test_data_types
fpc test_datatypes                    
fpc testdate                          
fpc test_defaultformat_settings       
fpc test_filemodes                    
fpc test_filename_parse               
fpc testformats                       
fpc testhttp                          
fpc test_jdate                        
fpc testmime
fpc testping                          
fpc testreg1                          
fpc testroute                         
fpc teststdinout                      
fpc testtprocess                      
fpc test_uc_animate                   
fpc test_uc_console                   
fpc test_uc_sageui                    
fpc test_ug_cgiout_ipc                
fpc test_ug_cgi                       
fpc test_ug_common                    
fpc test_ug_fileshare                 
fpc test_ug_ipc_file                  
fpc test_ug_ipc_xxxx_file             
fpc test_ug_jado02                    
fpc test_ug_jado                      
fpc test_ug_jcrypt                    
fpc test_ug_jegas                     
fpc test_ug_jfc_buffer                
fpc test_ug_jfc_dir                   
fpc test_ug_jfc_dl                    
fpc test_ug_jfc_fifo                  
fpc test_ug_jfc_ini                   
fpc test_ug_jfc_matrix                
fpc test_ug_jfc_tokenizer             
fpc test_ug_jfc_xdl                   
fpc test_ug_jfc_xml2                  
fpc test_ug_jfc_xml                   
fpc test_ug_jfilesys_01               
fpc test_ug_jfilesys_02               
fpc test_ug_jfilesys_03               
fpc test_ug_mysql                     
fpc test_ug_pixelgrid                 
fpc test_ug_rgba                      
fpc test_ug_threadmgr01               
fpc test_ug_threadmgr02               
fpc test_ug_threadmgr                 
fpc test_ug_usgs                      
fpc test_ug_xyz                       
fpc test_ug_zebra

